
name: 'health_platform'
version: '1.0.0'
config-version: 2

profile: 'health_platform'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  health_platform:
    # Config for all models
    materialized: view
    staging:
      # Config for staging models
      materialized: view
      schema: request_staging
    marts:
      # Config for marts models
      materialized: table
