# Template profiles.yml for Snowflake
# usage: export DBT_USER=... DBT_PASSWORD=... etc.

health_platform:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      database: HEALTH_PLATFORM_DB
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      schema: ANALYTICS
      threads: 4
      client_session_keep_alive: False
