name: "fhir_omop_dbt"
version: "0.1.0"
config-version: 2

profile: "fhir_omop"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  fhir_omop_dbt:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
