-- 1. Database Setup
-- Run as ACCOUNTADMIN or ROLE with CREATE DATABASE privilege

CREATE DATABASE IF NOT EXISTS HEALTH_PLATFORM_DB;
USE DATABASE HEALTH_PLATFORM_DB;

-- Create Schemas
CREATE SCHEMA IF NOT EXISTS RAW COMMENT = 'Landing area for raw JSON data from S3';
CREATE SCHEMA IF NOT EXISTS ANALYTICS COMMENT = 'Modeled data transformed by dbt';

-- Create File Format for NDJSON
CREATE OR REPLACE FILE FORMAT RAW.NDJSON_FORMAT
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = TRUE
    STRIP_OUTER_ARRAY = FALSE
    STRIP_NULL_VALUES = FALSE
    IGNORE_UTF8_ERRORS = FALSE;
